### ISSUE TITLE
Page: Build Home Page

### ISSUE THREAD

**Issue by daebert** [daebert/courseselect100#26]
![Bildschirmfoto 2021-06-13 um 15 52 29](https://user-images.githubusercontent.com/81586917/121810002-5ed66380-cc5f-11eb-97ba-8035525c76fd.png)

*** User Story
The user shall be able to select three course priorities. When he/ she calls the page for the first time he/she will see the three priority balls with three purple buttons "Hier klicken für Kurswahl" next to them. When he/she clicks on one of those buttons the user gets routet through the choice process for this priority. As soon as he/she has selected the priority, he/she will be routed back to the home page and the selection field of the resp. priority will have changed to course name and bin symbol. As soon as the user has chosen all three priorities the send button will be enabled and he/she will be able to send his/her choice for all three priorities.

*** Course Choice concept

- The website will receive an object with empty values {prio1: "", prio2: "", prio3:""}
- Rendering for priority fields: If value is "" render "Hier klicken für Kurswahl" Button, else render coursename and bin icon.
- Rending and function of submit button: If values for each priority is false (i.e. at least one priority value is not chosen), disable submit button, else enable submit button 

*** ToDo
- [ ] Setup Page Design
- [ ] Setup conditional rendering for course priorities
- [ ] setup link to next page for onclick of course choise button
- [ ] setup enable/disable function for senden button
